### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by zitterbewegung** [mroberts3000/SketchBasedShapeRetrieval#1]
Hi, what license is this source code under?

**Comment by mikeroberts3000** [comment]
Hrmm, I haven't given this much thought.

As far as I'm concerned, you are free to use the code for whatever purpose you see fit, subject to the following constraints. It is your responsibility to adhere to the licensing restrictions of the open source projects included here that aren't written by me (e.g., the Suggestive Contours application, to which I made minor modifications for this project). Furthermore, it is your responsibility to adhere to any intellectual property restrictions arising from the scholarly publications implemented in this project (e.g., "Sketch-Based Shape Retrieval" by Eitz et al.).

**Comment by zitterbewegung** [comment]
@mikeroberts3000 Thank you for the clarification.
